POST http://localhost:5000/api/wilder/2/skill/3/grade
Content-Type: application/json

{
  "rate": 1
}

###
GET http://localhost:5000/api/wilder/1/skill/1/grade

###
PUT http://localhost:5000/api/grade/13/update
Content-Type: application/json

{
  "rate": 14
}

###
DELETE http://localhost:5000/api/grade/10/delete